### PR TITLE
Change OmniFocus Message Links to Display Subject

### PR DESCRIPTION
**Pull request by rtull**
The bundle for OmniFocus was creating tasks with the `message://` URL appearing in the note raw instead of using the subject as the link presentation text, like the Things bundle does.

I've made some changes to the scripts so that new OmniFocus tasks are created with the message subject as the link display text (instead of the link itself) which I think is more desirable behavior.

### CODE REVIEW

**Comment by freron** [comment]
Thanks! Looks fine to me.

**Comment by freron** [comment]
Could you look into the issue reported here: https://freron.lighthouseapp.com/projects/58672/tickets/1310

Thanks in advance!

**Comment by infotexture** [comment]
Looks like these changes broke the commands as described in [MailMate ticket 1310](https://freron.lighthouseapp.com/projects/58672/tickets/1310) — I get the same error:

> Cannot insert an instance of “__NSCFString” into the characters array.

Any progress on a fix or rollback?

**Comment by rtull** [comment]
I'm terrible at managing GitHub notifications, as evidenced by the fact that I'm just now seeing this. Will do some investigation to see what I can find.

**Pull request merged**
